spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/db_projeto
spring.datasource.username=postgres
spring.datasource.password=marialinda
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081