server.port=8081

# Substitui as 5 linhas antigas por esta linha unificada:
spring.data.mongodb.uri=mongodb://admin:admin@localhost:27017/driveflow_db?authSource=admin

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG